version: "3.1"

services: 
  next_app:
    build: .
    container_name: next_app
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports: 
      - 3000:3000
      - 9229:9229
    environment:
      - COMMAND=${COMMAND}